package entidades;
// Generated 03-jul-2017 19:38:39 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HibernateSequence generated by hbm2java
 */
@Entity
@Table(name = "HIBERNATE_SEQUENCE", schema = "HR")
public class HibernateSequence implements java.io.Serializable {

	private HibernateSequenceId id;

	public HibernateSequence() {
	}

	public HibernateSequence(HibernateSequenceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tabla", column = @Column(name = "TABLA", nullable = false, length = 20)),
			@AttributeOverride(name = "siguiente", column = @Column(name = "SIGUIENTE", nullable = false, precision = 22, scale = 0)) })
	public HibernateSequenceId getId() {
		return this.id;
	}

	public void setId(HibernateSequenceId id) {
		this.id = id;
	}

}
