package entidades;
// Generated 03-jul-2017 19:38:39 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HibernateSequenceId generated by hbm2java
 */
@Embeddable
public class HibernateSequenceId implements java.io.Serializable {

	private String tabla;
	private BigDecimal siguiente;

	public HibernateSequenceId() {
	}

	public HibernateSequenceId(String tabla, BigDecimal siguiente) {
		this.tabla = tabla;
		this.siguiente = siguiente;
	}

	@Column(name = "TABLA", nullable = false, length = 20)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "SIGUIENTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSiguiente() {
		return this.siguiente;
	}

	public void setSiguiente(BigDecimal siguiente) {
		this.siguiente = siguiente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HibernateSequenceId))
			return false;
		HibernateSequenceId castOther = (HibernateSequenceId) other;

		return ((this.getTabla() == castOther.getTabla()) || (this.getTabla() != null && castOther.getTabla() != null
				&& this.getTabla().equals(castOther.getTabla())))
				&& ((this.getSiguiente() == castOther.getSiguiente()) || (this.getSiguiente() != null
						&& castOther.getSiguiente() != null && this.getSiguiente().equals(castOther.getSiguiente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTabla() == null ? 0 : this.getTabla().hashCode());
		result = 37 * result + (getSiguiente() == null ? 0 : this.getSiguiente().hashCode());
		return result;
	}

}
