package entidades;
// Generated 03-jul-2017 19:38:39 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegistroSecuencia generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_SECUENCIA", schema = "HR")
public class RegistroSecuencia implements java.io.Serializable {

	private BigDecimal id;

	public RegistroSecuencia() {
	}

	public RegistroSecuencia(BigDecimal id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
