package entidades;
// Generated 03-jul-2017 19:38:39 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * Registrotabla generated by hbm2java
 */
@Entity
@Table(name = "REGISTROTABLA", schema = "HR")
@TableGenerator (name = "adalid", table = "HIBERNATE_SEQUENCE", pkColumnName = "tabla", valueColumnName = "siguiente", allocationSize = 1, initialValue = 1)
public class Registrotabla implements java.io.Serializable {

	private BigDecimal id;

	public Registrotabla() {
	}

	public Registrotabla(BigDecimal id) {
		this.id = id;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.TABLE, generator = "adalid")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
