package entidades;
// Generated 03-jul-2017 19:38:39 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegistroUuid generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_UUID", schema = "HR")
public class RegistroUuid implements java.io.Serializable {

	private String id;

	public RegistroUuid() {
	}

	public RegistroUuid(String id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
